import { FollowupLead } from "@/types/followup"
import { addDays, subDays, startOfToday, formatISO } from "date-fns"

// ═══════════════════════════════════════════════════════════════════
// MOCK FOLLOW-UP / RESGATE 2 — exemplos funcionais simples
// ───────────────────────────────────────────────────────────────────
// Lista escrita à mão (não aleatória) para servir de sandbox/demonstração
// da tela /crm/followup-2. Cobre TODOS os estados possíveis de forma
// legível: status_followup, status_fechamento, temperatura e origem.
// Datas relativas a "hoje" para os filtros Hoje/Amanhã/Atrasados
// continuarem respondendo.
// ═══════════════════════════════════════════════════════════════════

const hoje = startOfToday()

// helper: data ISO em determinado dia/hora — exemplos com horário legível
const em = (data: Date, hora: number, minuto = 0) =>
  formatISO(new Date(data.getFullYear(), data.getMonth(), data.getDate(), hora, minuto, 0))

export const MOCK_FOLLOWUP_LEADS_2: FollowupLead[] = [
  // ── ATIVOS (dentro do ciclo, próximo disparo agendado) ─────────────
  {
    id: "f2_01",
    org_id: "org_demo",
    nome: "Ana Souza",
    telefone: "5511990000001",
    email: "ana.souza@example.com",
    origem: "meta_ads",
    utm_campaign: "implante-demo",
    status_followup: "ativo",
    status_fechamento: "em_aberto",
    temperatura: "quente",
    tentativa_atual: 1,
    max_tentativas: 8,
    proximo_envio: em(hoje, 9, 0), // hoje
    ultimo_contato: subDays(hoje, 1).toISOString(),
    ultimo_resumo: "Pediu valor do implante unitário. Aguardando retorno para agendar avaliação.",
    interesse: "Implante",
    recorrencia_ativa: false,
    created_at: subDays(hoje, 3).toISOString(),
    updated_at: subDays(hoje, 1).toISOString(),
  },
  {
    id: "f2_02",
    org_id: "org_demo",
    nome: "Bruno Lima",
    telefone: "5511990000002",
    email: "bruno.lima@example.com",
    origem: "google_ads",
    status_followup: "ativo",
    status_fechamento: "em_aberto",
    temperatura: "morno",
    tentativa_atual: 2,
    max_tentativas: 8,
    proximo_envio: em(addDays(hoje, 1), 10, 30), // amanhã
    ultimo_contato: subDays(hoje, 2).toISOString(),
    ultimo_resumo: "Comparou preço com outra clínica. Vamos reforçar diferenciais no próximo contato.",
    interesse: "Avaliação",
    recorrencia_ativa: false,
    created_at: subDays(hoje, 5).toISOString(),
    updated_at: subDays(hoje, 2).toISOString(),
  },
  {
    id: "f2_03",
    org_id: "org_demo",
    nome: "Carla Dias",
    telefone: "5511990000003",
    email: "carla.dias@example.com",
    origem: "whatsapp",
    status_followup: "ativo",
    status_fechamento: "em_aberto",
    temperatura: "frio",
    tentativa_atual: 3,
    max_tentativas: 8,
    proximo_envio: em(hoje, 14, 0), // hoje
    ultimo_contato: subDays(hoje, 1).toISOString(),
    ultimo_resumo: "Entrou pelo WhatsApp perguntando horário de funcionamento. Pouco engajamento até agora.",
    interesse: "Limpeza",
    recorrencia_ativa: false,
    created_at: subDays(hoje, 4).toISOString(),
    updated_at: subDays(hoje, 1).toISOString(),
  },
  {
    id: "f2_04",
    org_id: "org_demo",
    nome: "Diego Alves",
    telefone: "5511990000004",
    email: "diego.alves@example.com",
    origem: "organico",
    status_followup: "ativo",
    status_fechamento: "em_aberto",
    temperatura: "quente",
    tentativa_atual: 2,
    max_tentativas: 8,
    proximo_envio: em(addDays(hoje, 1), 16, 0), // amanhã
    ultimo_contato: subDays(hoje, 1).toISOString(),
    ultimo_resumo: "Chegou pelo site buscando clareamento. Demonstrou bastante interesse no pacote.",
    interesse: "Clareamento",
    recorrencia_ativa: false,
    created_at: subDays(hoje, 2).toISOString(),
    updated_at: subDays(hoje, 1).toISOString(),
  },
  {
    id: "f2_05",
    org_id: "org_demo",
    nome: "Elena Castro",
    telefone: "5511990000005",
    email: "elena.castro@example.com",
    origem: "indicacao",
    status_followup: "ativo",
    status_fechamento: "em_aberto",
    temperatura: "morno",
    tentativa_atual: 4,
    max_tentativas: 8,
    proximo_envio: em(addDays(hoje, 2), 9, 30), // depois de amanhã
    ultimo_contato: subDays(hoje, 1).toISOString(),
    ultimo_resumo: "Indicada por paciente atual. Interessada em ortodontia, ainda decidindo.",
    interesse: "Ortodontia",
    recorrencia_ativa: false,
    created_at: subDays(hoje, 6).toISOString(),
    updated_at: subDays(hoje, 1).toISOString(),
  },

  // ── VENCIDOS (disparo atrasado: proximo_envio no passado) ──────────
  {
    id: "f2_06",
    org_id: "org_demo",
    nome: "Felipe Nunes",
    telefone: "5511990000006",
    email: "felipe.nunes@example.com",
    origem: "meta_ads",
    utm_campaign: "avaliacao-demo",
    status_followup: "vencido",
    status_fechamento: "em_aberto",
    temperatura: "morno",
    tentativa_atual: 5,
    max_tentativas: 8,
    proximo_envio: em(subDays(hoje, 1), 11, 0), // ontem (atrasado)
    ultimo_contato: subDays(hoje, 3).toISOString(),
    ultimo_resumo: "Pediu para retomar contato na semana seguinte. Disparo programado ficou atrasado.",
    interesse: "Avaliação",
    recorrencia_ativa: false,
    created_at: subDays(hoje, 9).toISOString(),
    updated_at: subDays(hoje, 3).toISOString(),
  },
  {
    id: "f2_07",
    org_id: "org_demo",
    nome: "Gabriela Reis",
    telefone: "5511990000007",
    email: "gabriela.reis@example.com",
    origem: "offline",
    status_followup: "vencido",
    status_fechamento: "em_aberto",
    temperatura: "frio",
    tentativa_atual: 6,
    max_tentativas: 8,
    proximo_envio: em(subDays(hoje, 2), 15, 30), // 2 dias atrás (atrasado)
    ultimo_contato: subDays(hoje, 5).toISOString(),
    ultimo_resumo: "Cadastro veio de evento presencial. Não respondeu às últimas mensagens.",
    interesse: "Avaliação",
    recorrencia_ativa: false,
    created_at: subDays(hoje, 12).toISOString(),
    updated_at: subDays(hoje, 5).toISOString(),
  },

  // ── RESPONDEU (lead respondeu, ciclo pausa automaticamente) ────────
  {
    id: "f2_08",
    org_id: "org_demo",
    nome: "Heitor Pires",
    telefone: "5511990000008",
    email: "heitor.pires@example.com",
    origem: "whatsapp",
    status_followup: "respondeu",
    status_fechamento: "em_aberto",
    temperatura: "quente",
    tentativa_atual: 2,
    max_tentativas: 8,
    ultimo_contato: subDays(hoje, 1).toISOString(),
    ultimo_resumo: "Respondeu interessado e perguntou sobre formas de pagamento. Em tratativa com atendente.",
    interesse: "Implante",
    recorrencia_ativa: false,
    created_at: subDays(hoje, 4).toISOString(),
    updated_at: subDays(hoje, 1).toISOString(),
  },
  {
    id: "f2_09",
    org_id: "org_demo",
    nome: "Isabela Moraes",
    telefone: "5511990000009",
    email: "isabela.moraes@example.com",
    origem: "google_ads",
    status_followup: "respondeu",
    status_fechamento: "ganho",
    temperatura: "quente",
    tentativa_atual: 3,
    max_tentativas: 8,
    ultimo_contato: subDays(hoje, 1).toISOString(),
    ultimo_resumo: "Respondeu e fechou avaliação para esta semana. Lead convertido.",
    interesse: "Avaliação",
    recorrencia_ativa: false,
    created_at: subDays(hoje, 7).toISOString(),
    updated_at: subDays(hoje, 1).toISOString(),
  },

  // ── ESGOTADO (atingiu max_tentativas sem resposta) ─────────────────
  {
    id: "f2_10",
    org_id: "org_demo",
    nome: "João Vidal",
    telefone: "5511990000010",
    email: "joao.vidal@example.com",
    origem: "meta_ads",
    status_followup: "esgotado",
    status_fechamento: "perdido",
    temperatura: "frio",
    tentativa_atual: 8,
    max_tentativas: 8,
    ultimo_contato: subDays(hoje, 2).toISOString(),
    ultimo_resumo: "Não respondeu a nenhuma das 8 tentativas. Ciclo esgotado, lead perdido.",
    interesse: "Implante",
    recorrencia_ativa: false,
    created_at: subDays(hoje, 20).toISOString(),
    updated_at: subDays(hoje, 2).toISOString(),
  },
  {
    id: "f2_11",
    org_id: "org_demo",
    nome: "Karen Lopes",
    telefone: "5511990000011",
    email: "karen.lopes@example.com",
    origem: "offline",
    status_followup: "esgotado",
    status_fechamento: "perca",
    temperatura: "morno",
    tentativa_atual: 8,
    max_tentativas: 8,
    ultimo_contato: subDays(hoje, 3).toISOString(),
    ultimo_resumo: "Na última tentativa disse que desistiu do tratamento. Marcada como perca.",
    interesse: "Ortodontia",
    recorrencia_ativa: false,
    created_at: subDays(hoje, 18).toISOString(),
    updated_at: subDays(hoje, 3).toISOString(),
  },

  // ── ENCERRADO (ciclo concluído manualmente) ────────────────────────
  {
    id: "f2_12",
    org_id: "org_demo",
    nome: "Lucas Teixeira",
    telefone: "5511990000012",
    email: "lucas.teixeira@example.com",
    origem: "indicacao",
    status_followup: "encerrado",
    status_fechamento: "ganho",
    temperatura: "quente",
    tentativa_atual: 4,
    max_tentativas: 8,
    ultimo_contato: subDays(hoje, 6).toISOString(),
    ultimo_resumo: "Agendou e compareceu. Ciclo encerrado manualmente como ganho.",
    interesse: "Implante",
    recorrencia_ativa: true,
    created_at: subDays(hoje, 15).toISOString(),
    updated_at: subDays(hoje, 6).toISOString(),
  },
  {
    id: "f2_13",
    org_id: "org_demo",
    nome: "Marina Cunha",
    telefone: "5511990000013",
    email: "marina.cunha@example.com",
    origem: "meta_ads",
    utm_campaign: "implante-demo",
    status_followup: "encerrado",
    status_fechamento: "ganho",
    temperatura: "morno",
    tentativa_atual: 5,
    max_tentativas: 8,
    ultimo_contato: subDays(hoje, 8).toISOString(),
    ultimo_resumo: "Fechou pacote de clareamento após a quinta mensagem. Encerrado com sucesso.",
    interesse: "Clareamento",
    recorrencia_ativa: true,
    created_at: subDays(hoje, 16).toISOString(),
    updated_at: subDays(hoje, 8).toISOString(),
  },

  // ── PAUSADO (pausado manualmente pelo atendente) ───────────────────
  {
    id: "f2_14",
    org_id: "org_demo",
    nome: "Natália Brito",
    telefone: "5511990000014",
    email: "natalia.brito@example.com",
    origem: "whatsapp",
    status_followup: "pausado",
    status_fechamento: "em_aberto",
    temperatura: "frio",
    tentativa_atual: 3,
    max_tentativas: 8,
    ultimo_contato: subDays(hoje, 4).toISOString(),
    ultimo_resumo: "Pediu para pausar o contato — vai viajar. Retomar em duas semanas.",
    interesse: "Avaliação",
    recorrencia_ativa: false,
    created_at: subDays(hoje, 10).toISOString(),
    updated_at: subDays(hoje, 4).toISOString(),
  },
  {
    id: "f2_15",
    org_id: "org_demo",
    nome: "Otávio Ramos",
    telefone: "5511990000015",
    email: "otavio.ramos@example.com",
    origem: "google_ads",
    status_followup: "pausado",
    status_fechamento: "em_aberto",
    temperatura: "morno",
    tentativa_atual: 1,
    max_tentativas: 8,
    ultimo_contato: subDays(hoje, 2).toISOString(),
    ultimo_resumo: "Pausado para revisão do roteiro de mensagens da campanha.",
    interesse: "Limpeza",
    recorrencia_ativa: false,
    created_at: subDays(hoje, 6).toISOString(),
    updated_at: subDays(hoje, 2).toISOString(),
  },
]
