// Utilitário de tema/cores para status de veiculação (delivery)
// Códigos canônicos alinhados com backend meta_delivery.py

export const VEICULACAO_ATIVO = 'ATIVO'
export const VEICULACAO_DESATIVADO = 'DESATIVADO'
export const VEICULACAO_CONCLUIDO = 'CONCLUIDO'
export const VEICULACAO_PROGRAMADO = 'PROGRAMADO'
export const VEICULACAO_APRENDIZADO = 'APRENDIZADO'
export const VEICULACAO_APRENDIZADO_LIMITADO = 'APRENDIZADO_LIMITADO'
export const VEICULACAO_EM_ANALISE = 'EM_ANALISE'
export const VEICULACAO_REJEITADO = 'REJEITADO'
export const VEICULACAO_PROCESSANDO = 'PROCESSANDO'
export const VEICULACAO_ERRO_CONTA = 'ERRO_CONTA'
export const VEICULACAO_ITENS_AUSENTES = 'ITENS_AUSENTES'

export type CodigoVeiculacao =
  | typeof VEICULACAO_ATIVO
  | typeof VEICULACAO_DESATIVADO
  | typeof VEICULACAO_CONCLUIDO
  | typeof VEICULACAO_PROGRAMADO
  | typeof VEICULACAO_APRENDIZADO
  | typeof VEICULACAO_APRENDIZADO_LIMITADO
  | typeof VEICULACAO_EM_ANALISE
  | typeof VEICULACAO_REJEITADO
  | typeof VEICULACAO_PROCESSANDO
  | typeof VEICULACAO_ERRO_CONTA
  | typeof VEICULACAO_ITENS_AUSENTES

export const GRUPO_OPERACIONAL = 'operacional'
export const GRUPO_PERFORMANCE = 'performance'
export const GRUPO_SISTEMICO = 'sistemico'

export type GrupoVeiculacao =
  | typeof GRUPO_OPERACIONAL
  | typeof GRUPO_PERFORMANCE
  | typeof GRUPO_SISTEMICO

export const VEICULACAO_GRUPO: Record<CodigoVeiculacao, GrupoVeiculacao> = {
  [VEICULACAO_ATIVO]: GRUPO_OPERACIONAL,
  [VEICULACAO_DESATIVADO]: GRUPO_OPERACIONAL,
  [VEICULACAO_CONCLUIDO]: GRUPO_OPERACIONAL,
  [VEICULACAO_PROGRAMADO]: GRUPO_OPERACIONAL,
  [VEICULACAO_APRENDIZADO]: GRUPO_PERFORMANCE,
  [VEICULACAO_APRENDIZADO_LIMITADO]: GRUPO_PERFORMANCE,
  [VEICULACAO_EM_ANALISE]: GRUPO_SISTEMICO,
  [VEICULACAO_REJEITADO]: GRUPO_SISTEMICO,
  [VEICULACAO_PROCESSANDO]: GRUPO_SISTEMICO,
  [VEICULACAO_ERRO_CONTA]: GRUPO_SISTEMICO,
  [VEICULACAO_ITENS_AUSENTES]: GRUPO_SISTEMICO,
}

export const VEICULACAO_LABEL: Record<CodigoVeiculacao, string> = {
  [VEICULACAO_ATIVO]: 'Ativo',
  [VEICULACAO_DESATIVADO]: 'Desativado',
  [VEICULACAO_CONCLUIDO]: 'Concluído',
  [VEICULACAO_PROGRAMADO]: 'Programado',
  [VEICULACAO_APRENDIZADO]: 'Aprendendo',
  [VEICULACAO_APRENDIZADO_LIMITADO]: 'Aprendizado Limitado',
  [VEICULACAO_EM_ANALISE]: 'Em Análise',
  [VEICULACAO_REJEITADO]: 'Rejeitado',
  [VEICULACAO_PROCESSANDO]: 'Processando',
  [VEICULACAO_ERRO_CONTA]: 'Erro na Conta',
  [VEICULACAO_ITENS_AUSENTES]: 'Itens Ausentes',
}

export const VEICULACAO_COR: Record<CodigoVeiculacao, string> = {
  [VEICULACAO_ATIVO]: '#0fa856',
  [VEICULACAO_APRENDIZADO]: '#0fa856',
  [VEICULACAO_DESATIVADO]: '#8892b0',
  [VEICULACAO_CONCLUIDO]: '#8892b0',
  [VEICULACAO_PROGRAMADO]: '#8892b0',
  [VEICULACAO_APRENDIZADO_LIMITADO]: '#EF9F27',
  [VEICULACAO_EM_ANALISE]: '#EF9F27',
  [VEICULACAO_REJEITADO]: '#FF5C8D',
  [VEICULACAO_ERRO_CONTA]: '#FF5C8D',
  [VEICULACAO_PROCESSANDO]: '#8892b0',
  [VEICULACAO_ITENS_AUSENTES]: '#8892b0',
}

export const VEICULACAO_COR_BG: Record<CodigoVeiculacao, string> = {
  [VEICULACAO_ATIVO]: 'rgba(15,168,86,0.10)',
  [VEICULACAO_APRENDIZADO]: 'rgba(15,168,86,0.10)',
  [VEICULACAO_DESATIVADO]: 'rgba(136,146,176,0.10)',
  [VEICULACAO_CONCLUIDO]: 'rgba(136,146,176,0.10)',
  [VEICULACAO_PROGRAMADO]: 'rgba(136,146,176,0.10)',
  [VEICULACAO_APRENDIZADO_LIMITADO]: 'rgba(239,159,39,0.10)',
  [VEICULACAO_EM_ANALISE]: 'rgba(239,159,39,0.10)',
  [VEICULACAO_REJEITADO]: 'rgba(255,92,141,0.10)',
  [VEICULACAO_ERRO_CONTA]: 'rgba(255,92,141,0.10)',
  [VEICULACAO_PROCESSANDO]: 'rgba(136,146,176,0.10)',
  [VEICULACAO_ITENS_AUSENTES]: 'rgba(136,146,176,0.10)',
}

export const VEICULACAO_COR_BORDER: Record<CodigoVeiculacao, string> = {
  [VEICULACAO_ATIVO]: 'rgba(15,168,86,0.25)',
  [VEICULACAO_APRENDIZADO]: 'rgba(15,168,86,0.25)',
  [VEICULACAO_DESATIVADO]: 'rgba(136,146,176,0.20)',
  [VEICULACAO_CONCLUIDO]: 'rgba(136,146,176,0.20)',
  [VEICULACAO_PROGRAMADO]: 'rgba(136,146,176,0.20)',
  [VEICULACAO_APRENDIZADO_LIMITADO]: 'rgba(239,159,39,0.25)',
  [VEICULACAO_EM_ANALISE]: 'rgba(239,159,39,0.25)',
  [VEICULACAO_REJEITADO]: 'rgba(255,92,141,0.25)',
  [VEICULACAO_ERRO_CONTA]: 'rgba(255,92,141,0.25)',
  [VEICULACAO_PROCESSANDO]: 'rgba(136,146,176,0.20)',
  [VEICULACAO_ITENS_AUSENTES]: 'rgba(136,146,176,0.20)',
}

export interface ConfigVeiculacao {
  label: string
  cor: string
  corBg: string
  corBorder: string
  grupo: GrupoVeiculacao
}

export function configVeiculacao(codigo: string): ConfigVeiculacao {
  const c = codigo as CodigoVeiculacao
  return {
    label: VEICULACAO_LABEL[c] || codigo,
    cor: VEICULACAO_COR[c] || '#8892b0',
    corBg: VEICULACAO_COR_BG[c] || 'rgba(136,146,176,0.10)',
    corBorder: VEICULACAO_COR_BORDER[c] || 'rgba(136,146,176,0.20)',
    grupo: VEICULACAO_GRUPO[c] || GRUPO_SISTEMICO,
  }
}

// Opções para dropdown agrupado
export const OPCOES_VEICULACAO = [
  {
    grupo: 'Operacionais',
    opcoes: [
      { codigo: VEICULACAO_ATIVO, label: VEICULACAO_LABEL[VEICULACAO_ATIVO] },
      { codigo: VEICULACAO_DESATIVADO, label: VEICULACAO_LABEL[VEICULACAO_DESATIVADO] },
      { codigo: VEICULACAO_CONCLUIDO, label: VEICULACAO_LABEL[VEICULACAO_CONCLUIDO] },
      { codigo: VEICULACAO_PROGRAMADO, label: VEICULACAO_LABEL[VEICULACAO_PROGRAMADO] },
    ],
  },
  {
    grupo: 'Performance',
    opcoes: [
      { codigo: VEICULACAO_APRENDIZADO, label: VEICULACAO_LABEL[VEICULACAO_APRENDIZADO] },
      { codigo: VEICULACAO_APRENDIZADO_LIMITADO, label: VEICULACAO_LABEL[VEICULACAO_APRENDIZADO_LIMITADO] },
    ],
  },
  {
    grupo: 'Sistêmicos',
    opcoes: [
      { codigo: VEICULACAO_EM_ANALISE, label: VEICULACAO_LABEL[VEICULACAO_EM_ANALISE] },
      { codigo: VEICULACAO_REJEITADO, label: VEICULACAO_LABEL[VEICULACAO_REJEITADO] },
      { codigo: VEICULACAO_PROCESSANDO, label: VEICULACAO_LABEL[VEICULACAO_PROCESSANDO] },
      { codigo: VEICULACAO_ERRO_CONTA, label: VEICULACAO_LABEL[VEICULACAO_ERRO_CONTA] },
      { codigo: VEICULACAO_ITENS_AUSENTES, label: VEICULACAO_LABEL[VEICULACAO_ITENS_AUSENTES] },
    ],
  },
]
